### ISSUE TITLE
你好, 请问最大连接设备个数只能是5个吗? 

### ISSUE THREAD

**Issue by MAIMIHO** [eson-yunfei/AndroidBle#13]
请问Android 手机最多能连接多少个BLE设备? 
有些地方说7个, 有些地方说很多个. 
多谢!

**Comment by eson-yunfei** [comment]
Android最大连接数不是5个。我这里设置的5个，是个人在测试的时候感觉比较稳定的数目，和Android实际最大连接数无关。
关于最大连接的个数，有的说是7个有的说是6个，具体应该和手机采用的蓝牙模块有关系。

**Comment by MAIMIHO** [comment]
你好, jitpack上面最新的是0.9, 最近有计划更新这个库吗?

**Comment by eson-yunfei** [comment]
JitPack上面最新版本是v1.0 。
后续会更新。欢迎提供建议。
